name: first
on: push
jobs:
  build:
    name: Build job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Say hello
        run: echo "Hello"