name: first
on: push
jobs:
  job-one:
    name: Build job one
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Say hello
        run: echo "Hello ubuntu"
  job-two:
    name: Build job two
    runs-on: windows-latest
    needs: job-one
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Say hello
        run: echo "Hello windows"
