name: Spring boot
on: push
env:
  FILE_NAME: demo-0.0.1-SNAPSHOT.jar
jobs:
  build-jar:
    name: Build jar
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Java Env
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
          java-package: jdk
      - name: Grant permission
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: spring-boot-app
          path: ./build/libs/${{ env.FILE_NAME }}
