name: Spring boot
on: [push, workflow_dispatch]
env:
  FILE_NAME: demo-0.0.1-SNAPSHOT.jar
jobs:
  build-jar:
    name: Build jar
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run check style
        uses: nikitasavinov/checkstyle-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: 'github-pr-check'
          tool_name: 'testtool'
      - name: Setup Java Env
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
          java-package: jdk
      - name: Grant permission
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: spring-boot-app
          path: ./build/libs/${{ env.FILE_NAME }}
  test-jar:
    name: Test jar file
    runs-on: ubuntu-latest
    needs: build-jar
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: spring-boot-app
      - name: View file
        run: ls
